repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: ^charts/web-app/templates/
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: helm-lint
        name: helm lint
        entry: helm lint charts/web-app
        language: system
        pass_filenames: false
