nameOverride: ""
fullnameOverride: ""

image:
  repository: sre-gitops/app
  tag: "main"
  pullPolicy: IfNotPresent

replicaCount: 1

environment: "dev"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: web-app.local
      path: /
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  readiness:
    initialDelaySeconds: 2
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - ALL

prometheus:
  scrape: true
  path: /metrics
  port: 8080
