apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-dev
  namespace: argocd
spec:
  project: web-app-dev
  source:
    repoURL: "https://github.com/ahmedbadawy4/sre-gitops.git"
    targetRevision: "main"
    path: charts/web-app
    helm:
      valueFiles:
        - ../values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
